service: hbt-quarkus-demo

provider:
  name: aws
  runtime: java11
  stage: hbt
  region: eu-central-1
  endpointType: REGIONAL
  memorySize: 1024
  timeout: 30
  deploymentBucket: dasniko-quarkus-demo
  environment:
    DYNAMODB_TABLE: quarkus-books-sls
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  quarkus:
    handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
    events:
      - http:
          path: /{proxy+}
          method: any
          authorizer:
            name: basicAuth
            type: token
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 300
    package:
      artifact: target/function.zip
  basicAuth:
    handler: js/basicAuthorizer.handler
    runtime: nodejs12.x
    memorySize: 128
    package:
      exclude:
        - .idea/**
        - .mvn/**
        - src/**
        - target/**
        - '*.*ml'

package:
  individually: true

resources:
  Resources:
    DynamoDBBooks:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    GatewayResponse:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: ApiGatewayRestApi
        StatusCode: 401